### ISSUE TITLE
Fix jenkins plugins installation

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/EtCaterva-Ansible#35]
It's only possible the first time. After that, it will fail to authenticate

**Comment by palvarez89** [comment]
Possible idea: Create an ssh private-key and add the public key to the jenkins user, to use that key after for CLI commands (installing plugins)

**Comment by palvarez89** [comment]
It might be easier to create a password for an user (random pass), store it into a file, and then log in for CLI calls like this:

    java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ who-am-i --username theuser --password thepassword


Note: `--password-file` is an option too.

**Comment by Mariocj89** [comment]
Use "closes #number" to close an issue when the por is closed

**Comment by palvarez89** [comment]
Closes https://github.com/etcaterva/EtCaterva-Ansible/issues/36

**Comment by palvarez89** [comment]
I need to learn github workflow... :/
